# try-catch-python
error boundaries in python
